services:
  - type: web
    name: deadline-os-backend
    env: python
    region: ohio
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()' --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT"
    pythonVersion: 3.13.0
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: "https://deadlineos.vercel.app"
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
