import os
import re

BACKEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
MIGRATION_FILE = os.path.join(BACKEND_DIR, 'migrations', 'versions', 'a37ac0618419_phase_1_runtime_models.py')

def main():
    print("--- Milestone 0: Fixing Runtime Migration ---")
    
    with open(MIGRATION_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract header part
    match = re.search(r"def upgrade\(\)(?:.*?)def downgrade\(\)", content, re.DOTALL)
    if not match:
        print("Could not find upgrade/downgrade blocks")
        return
        
    new_upgrade_code = '''def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_states', schema=None) as batch_op:
        batch_op.create_index('idx_runtime_states_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_runtime_states_user_active', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_states_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_states_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_states_user_id'), ['user_id'], unique=False)

    op.create_table('runtime_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('runtime_state_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('planned_duration_sec', sa.Integer(), nullable=False),
    sa.Column('paused_duration_sec', sa.Integer(), nullable=False),
    sa.Column('completion_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['runtime_state_id'], ['runtime_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_sessions_runtime_state_id'), ['runtime_state_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runtime_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_sessions_runtime_state_id'))

    op.drop_table('runtime_sessions')
    with op.batch_alter_table('runtime_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_runtime_states_entity_type'))
        batch_op.drop_index(batch_op.f('ix_runtime_states_entity_id'))
        batch_op.drop_index('idx_runtime_states_user_active')
        batch_op.drop_index('idx_runtime_states_entity')

    op.drop_table('runtime_states')
    op.drop_table('runtime_outbox_events')
    # ### end Alembic commands ###
'''
    
    content = re.sub(r"def upgrade\(\).*?def downgrade\(\).*?(?=\Z)", new_upgrade_code, content, flags=re.DOTALL)
    
    with open(MIGRATION_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print("Fixed migration file.")

if __name__ == "__main__":
    main()
