"""
DeadlineOS — Intervention Model
===============================
Persists active and resolved interventions generated by the Intervention Engine.
"""

import uuid
from datetime import datetime, timezone
from database.db import db

class Intervention(db.Model):
    __tablename__ = "interventions"
    
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = db.Column(db.String(36), nullable=False, index=True)
    type = db.Column(db.String(50), nullable=False) # procrastination, rescue, twin_forecast, calendar_overload, accountability
    severity = db.Column(db.String(20), nullable=False) # Critical, High, Medium, Low
    priority_score = db.Column(db.Integer, default=0) # 0-100
    confidence_score = db.Column(db.Integer, default=0) # 0-100
    trigger_source = db.Column(db.String(100), nullable=False) # e.g., 'Digital Twin Forecast', 'Accountability Analytics'
    message = db.Column(db.Text, nullable=False)
    recommended_action = db.Column(db.JSON, nullable=False) # e.g., {"action": "reschedule", "target": "Task_A", "suggested_time": "14:00"}
    
    created_at = db.Column(db.DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    resolved = db.Column(db.Boolean, default=False)
    resolved_at = db.Column(db.DateTime, nullable=True)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "type": self.type,
            "severity": self.severity,
            "priority_score": self.priority_score,
            "confidence_score": self.confidence_score,
            "trigger_source": self.trigger_source,
            "message": self.message,
            "recommended_action": self.recommended_action,
            "created_at": self.created_at.isoformat(),
            "resolved": self.resolved,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None
        }

class Threat(db.Model):
    __tablename__ = "threats"
    
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = db.Column(db.String(36), nullable=False, index=True)
    type = db.Column(db.String(50), nullable=False)
    severity = db.Column(db.String(20), nullable=False)
    source = db.Column(db.String(100), nullable=False)
    message = db.Column(db.Text, nullable=False)
    details = db.Column(db.JSON, nullable=True)
    status = db.Column(db.String(20), default="active")
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "type": self.type,
            "severity": self.severity,
            "source": self.source,
            "message": self.message,
            "details": self.details,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None
        }
