"""Baseline Phase 0

Revision ID: 27ae92747f99
Revises: 
Create Date: 2026-08-09 11:16:20.644736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27ae92747f99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rescue_executions')
    op.drop_table('system_snapshots')
    op.drop_table('rescue_plans')
    with op.batch_alter_table('accountability_metrics', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_accountability_metrics_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('agent_execution_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_agent_execution_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('coach_reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_coach_reports_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('execution_profiles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_execution_profiles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_habit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_habits_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_milestones_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('orchestrator_events', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_orchestrator_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reflection_reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_reflection_reports_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_schedule_slots_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_schedules_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('threats', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_threats_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_threats_user'), type_='foreignkey')
        batch_op.drop_column('resolved_at')

    with op.batch_alter_table('twin_simulation_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_twin_simulation_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('working_hours_start',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'09:00'::character varying"))
        batch_op.alter_column('working_hours_end',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'17:00'::character varying"))
        batch_op.alter_column('focus_hours_start',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('focus_hours_end',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('preferred_planning_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'balanced'::character varying"))
        batch_op.alter_column('theme_preference',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'system'::character varying"))

    with op.batch_alter_table('weekly_reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_weekly_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reviews_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme_preference',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
        batch_op.alter_column('preferred_planning_mode',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'balanced'::character varying"))
        batch_op.alter_column('focus_hours_end',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('focus_hours_start',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('working_hours_end',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'17:00'::character varying"))
        batch_op.alter_column('working_hours_start',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'09:00'::character varying"))

    with op.batch_alter_table('twin_simulation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twin_simulation_logs_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('threats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_threats_user'), 'users', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_threats_user_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_slots_user_id'))
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('reflection_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reflection_reports_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('orchestrator_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orchestrator_events_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_logs_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('execution_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_profiles_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('coach_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_reports_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('agent_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_execution_logs_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('accountability_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accountability_metrics_user_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('rescue_plans',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('success_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intervention', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rescue_plans_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('rescue_plans_pkey'))
    )
    op.create_table('system_snapshots',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tasks_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('goals_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('habits_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('schedule_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_system_snapshots_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('system_snapshots_pkey'))
    )
    op.create_table('rescue_executions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_response', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('snapshot_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('strategy_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('executed_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'executed'::character varying"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rescue_executions_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('rescue_executions_pkey'))
    )
    # ### end Alembic commands ###
