"""Phase 1 Runtime Models

Revision ID: a37ac0618419
Revises: 27ae92747f99
Create Date: 2026-08-09 11:17:15.544933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a37ac0618419'
down_revision = '27ae92747f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_states', schema=None) as batch_op:
        batch_op.create_index('idx_runtime_states_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_runtime_states_user_active', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_states_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_states_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_states_user_id'), ['user_id'], unique=False)

    op.create_table('runtime_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('runtime_state_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('planned_duration_sec', sa.Integer(), nullable=False),
    sa.Column('paused_duration_sec', sa.Integer(), nullable=False),
    sa.Column('completion_source', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['runtime_state_id'], ['runtime_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runtime_sessions_runtime_state_id'), ['runtime_state_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runtime_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_sessions_runtime_state_id'))

    op.drop_table('runtime_sessions')
    with op.batch_alter_table('runtime_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_runtime_states_entity_type'))
        batch_op.drop_index(batch_op.f('ix_runtime_states_entity_id'))
        batch_op.drop_index('idx_runtime_states_user_active')
        batch_op.drop_index('idx_runtime_states_entity')

    op.drop_table('runtime_states')
    op.drop_table('runtime_outbox_events')
    # ### end Alembic commands ###
